on: [push, pull_request]

name: cover

jobs:
  cover:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUBPAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Install arrow
        run: install.packages("arrow")
	shell: Rscript {0}

      - name: Try arrow
        run: arrow::write_parquet(mtcars, tempfile())
	shell: Rscript {0}
